const SUCCESS_STATUS=200
const ERROR_STATUS=500
const OK_STATUS=201
const INSERT_MESSAGE="Inserted Successfully"
const UPDATE_MESSAGE="updated Successfully"
const DELETE_MESSAGE="deleted Successfully"
const SELECT_MESSAGE="selected Successfully"
const ALREADY_EXISTS="already exists kindly change your mail id"
const MISSING_RECORD="No such record is present in database"
const INCORRECT_FORMAT="Input data is not in the correct format."
module.exports={SUCCESS_STATUS,ERROR_STATUS,OK_STATUS,INSERT_MESSAGE,UPDATE_MESSAGE,DELETE_MESSAGE,SELECT_MESSAGE,ALREADY_EXISTS,MISSING_RECORD,INCORRECT_FORMAT}